create database if not exists BLOG;
use BLOG;

CREATE TABLE Admin(
   ID_ADMIN INT not null auto_increment,
   NOM_ADMIN VARCHAR(50) NOT NULL,
   PASSWORD_ADMIN VARCHAR(50) NOT NULL,
   PRIMARY KEY(ID_ADMIN)
)Engine = InnoDB CHARSET=utf8 COLLATE utf8_unicode_ci;

CREATE TABLE CATEGORIE(
   CODE_TYPE_ART CHAR(6) not null,
   LIB_TYPE_ART VARCHAR(50) NOT NULL,
   PRIMARY KEY(CODE_TYPE_ART)
)Engine = InnoDB CHARSET=utf8 COLLATE utf8_unicode_ci;

CREATE TABLE UTILISATEUR(
   ID_UTILISATEUR INT not null auto_increment,
   PSEUDO_UTILISATEUR VARCHAR(50) NOT NULL,
   EMAIL_UTILISATEUR VARCHAR(100),
   ABONNE_NEWS boolean not null,
   PRIMARY KEY(ID_UTILISATEUR)
)Engine = InnoDB CHARSET=utf8 COLLATE utf8_unicode_ci;

CREATE TABLE Article(
   ID_ARTICLE INT not null auto_increment,
   TITRE_ARTICLE VARCHAR(50) NOT NULL,
   DATE_PUBLICATION DATETIME NOT NULL,
   CONTENU_ARTICLE TEXT NOT NULL,
   REF_IMAGE VARCHAR(50) NOT NULL,
   RESUME_ART TEXT NOT NULL,
   REPONSE_ART boolean NOT NULL,
   CODE_TYPE_ART CHAR(6) NOT NULL,
   ID_ADMIN INT NOT NULL,
   PRIMARY KEY(ID_ARTICLE),
   FOREIGN KEY(CODE_TYPE_ART) REFERENCES CATEGORIE(CODE_TYPE_ART),
   FOREIGN KEY(ID_ADMIN) REFERENCES Admin(ID_ADMIN)
)Engine = InnoDB CHARSET=utf8 COLLATE utf8_unicode_ci;

CREATE TABLE Commentaire(
   ID_COMMENTAIRE INT not null auto_increment,
   CONTENU_COMMENTAIRE TEXT NOT NULL,
   DATE_COMMENTAIRE DATETIME NOT NULL,
   ID_ARTICLE INT NOT NULL,
   ID_UTILISATEUR INT NOT NULL,
   PRIMARY KEY(ID_COMMENTAIRE),
   FOREIGN KEY(ID_ARTICLE) REFERENCES Article(ID_ARTICLE),
   FOREIGN KEY(ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR)
)Engine = InnoDB CHARSET=utf8 COLLATE utf8_unicode_ci;

CREATE TABLE Vote(
   ID_VOTE INT not null auto_increment,
   CPT_VOTE_INTOX INT,
   CPT_VOTE_INFO INT,
   ID_ARTICLE INT NOT NULL,
   PRIMARY KEY(ID_VOTE),
   FOREIGN KEY(ID_ARTICLE) REFERENCES Article(ID_ARTICLE)
)Engine = InnoDB CHARSET=utf8 COLLATE utf8_unicode_ci;
